language: python
cache: pip
python:
  - "3.6"
sudo: true
env:
  global:
    - USE_TRAVIS=true
dist: xenial
services:
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database test;' -U postgres
#  - python fake_judger.py
install:
  - pip install -r backend/requirements.txt
script:
  - cd backend/
  - python -m unittest testcases.usertest
  - python -m unittest testcases.dbtest
#  - python -m unittest testcases.problemtest
  - python -m unittest testcases.recordtest
  - python -m unittest testcases.ratiotest
  - python -m unittest testcases.noticetest
  - python -m unittest testcases.homeworktest
  - python -m unittest testcases.coursetest
