language: python
cache: pip
python:
  - "3.6"
sudo: true
env:
  global:
    - USE_TRAVIS=true
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
install:
  - pip install -r backend/requirements.txt
script:
  - cd backend/
  - python ./pycharm_runner/_jb_unittest_runner.py --target testcases.usertest.UserTest

