version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - frontend
    restart: always
    environment:
      DOMAINS: '308469.iterator-traits.com -> http://frontend:80'
      WORKER_PROCESSES: 2
      WORKER_CONNECTIONS: 4096
      CLIENT_MAX_BODY_SIZE: '500M'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'

  tornado_web:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - postgres
    links:
      - postgres
      
  postgres:
    restart: always
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/

  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    volumes:
      - './backend/root/judge_html_temp:/usr/src/app/root/judge_html_temp'
    # ports:
      # - '80:80'

  judger:
    build: ./judger
    expose:
      - "12345"
    cap_add:
      - SYS_PTRACE
    volumes:
      - './backend/root:/usr/src/app/root'
      - './backend/test:/usr/src/app/test'
      - './backend/judge_script:/usr/src/app/judge_script'